Feature/j 3
Lerinskaya/JS-slider-calculator-timer pull request #3
Opened 2022-08-08 09:14 UTC by Lerinskaya

2022-08-08 18:48 UTC, i-barysiuk requested changes

2022-08-08 18:48 UTC, i-barysiuk commented on src/css/calc.scss
> +
Когда код будет смотреть новичек ему будет очень сложно догадаться до того что общие стили проекта лежат в файлике стилей калькулятора :)

Давай сделаем красиво и вынесем в отдельный файлик common.scss все стили которые относятся ко всему проекту, даже если он будет один или как в нашем случае два

2022-08-08 18:48 UTC, i-barysiuk commented on src/css/pomodoro.scss
> +}
Это тоже можно вынести в фалик коммон и даже заметишь что есть лишнее свойство

2022-08-08 18:48 UTC, i-barysiuk commented on src/css/pomodoro.scss
> +$white2: rgb(213, 219, 222);
BEST PRACTICE:

Когда в проекте появляется первый white2 можно начинать кричать потому что это несравненно приведет к тому что позже в проекте появятся white3 white4 и так далее. 

Из бест практисов лучшим вариантом считается использование либо индивидуальных названий цветов либо их дизайн кодов. 

Текущее -> Название цвета -> дизайн код
white -> aliceblue -> W100
white2 -> smoke-white -> W200

Я говорю про конкретное название переменных, можно выбрать любой из вариантов согласно удобству на проекте но лучше их не комбинировать. Это удобно потому что позже тебе будет легче синхронизироваться с дизайн макетом выбирать между white1-5 сложнее чем из названия самого цвета или его кодового дизайн назначения по дизайн макету

2022-08-08 18:48 UTC, i-barysiuk commented on src/js/calc.js
> +});
Сможешь объяснить почему у тебя в результат пишется 0. а не .0?

2022-08-08 18:48 UTC, i-barysiuk commented on src/js/pomodoro.js
> +});
Словил кейс интересный. Если я в режиме отдыха и нажимаю кнопку сброс меняется время на 2 минуты. 

Ожидается либо сброс времени до 1 минуты и я так же в режиме отдыха или сброс времени на 2 минуты но я переключаюсь в режим работы по умолчанию. 

Можешь считать что к проекту подключился тестировщик и дал тебе такой фидбэк)

2022-08-08 18:48 UTC, i-barysiuk commented on src/js/pomodoro.js
> +
Не совсем понимаю зачем мы минусуем единичку дважды 
1 раз в html 
2 раз в переменной минуты

Так же словил странный баг, если я запустил таймер и нажал минус то у меня время минусуется дважды, если с жтим разберемся и исправим будет хорошо

2022-08-09 06:32 UTC, Lerinskaya commented on src/js/pomodoro.js
> +
Здесь отнимаю от minutes.innerHTML, потому что в начале отсчета секундам присваивается 59 всегда. Т.е. например установили 11 минут, при нажатии на старт будет принимать минуты как 11- 1 , а секунды 59.

2022-08-09 06:34 UTC, Lerinskaya commented on src/js/calc.js
> +});
Возможно потому что сначала проверяется условие и ему присваивается значение, а потом уже записывается результат клика)

2022-08-09 18:07 UTC, i-barysiuk commented on src/js/calc.js
> +});
нет) У тебя по конпе точки вызывается две функции одна с добавлением нуля и та которая общая для калькулятора. 

Важен порядок. Вызовы клика идут от самого глубокого элемента к самому верхнему html - это называется всплытие

2022-08-09 18:11 UTC, i-barysiuk approved these changes

2022-11-04 09:07 UTC, merged